import type { FileOptions, MkdirOptions, ReadDirItem, DownloadResult, StatResult, FSInfoResult, DownloadFileOptions, UploadFileOptions, UploadResult } from "./types";
export * from "./types";
declare var RNFS: {
    mkdir(filepath: string, options?: MkdirOptions): Promise<void>;
    moveFile(filepath: string, destPath: string, options?: FileOptions): Promise<void>;
    copyFile(filepath: string, destPath: string, options?: FileOptions): Promise<void>;
    pathForBundle(bundleNamed: string): Promise<string>;
    pathForGroup(groupName: string): Promise<string>;
    getFSInfo(): Promise<FSInfoResult>;
    getAllExternalFilesDirs(): Promise<string>;
    unlink(filepath: string): Promise<void>;
    exists(filepath: string): Promise<boolean>;
    stopDownload(jobId: number): void;
    resumeDownload(jobId: number): void;
    isResumable(jobId: number): Promise<boolean>;
    stopUpload(jobId: number): void;
    completeHandlerIOS(jobId: number): void;
    readDir(dirpath: string): Promise<ReadDirItem[]>;
    readDirAssets(dirpath: string): Promise<ReadDirItem[]>;
    existsAssets(filepath: string): any;
    existsRes(filename: string): any;
    readdir(dirpath: string): Promise<string[]>;
    setReadable(filepath: string, readable: boolean, ownerOnly: boolean): Promise<boolean>;
    stat(filepath: string): Promise<StatResult>;
    readFile(filepath: string, encodingOrOptions?: any): Promise<string>;
    read(filepath: string, length?: number, position?: number, encodingOrOptions?: any): Promise<string>;
    readFileAssets(filepath: string, encodingOrOptions?: any): Promise<string>;
    readFileRes(filename: string, encodingOrOptions?: any): Promise<string>;
    hash(filepath: string, algorithm: string): Promise<string>;
    copyFileAssets(filepath: string, destPath: string): any;
    copyFileRes(filename: string, destPath: string): any;
    copyAssetsFileIOS(imageUri: string, destPath: string, width: number, height: number, scale?: number, compression?: number, resizeMode?: string): Promise<string>;
    copyAssetsVideoIOS(imageUri: string, destPath: string): Promise<string>;
    writeFile(filepath: string, contents: string, encodingOrOptions?: any): Promise<void>;
    appendFile(filepath: string, contents: string, encodingOrOptions?: any): Promise<void>;
    write(filepath: string, contents: string, position?: number, encodingOrOptions?: any): Promise<void>;
    downloadFile(options: DownloadFileOptions): {
        jobId: number;
        promise: Promise<DownloadResult>;
    };
    uploadFiles(options: UploadFileOptions): {
        jobId: number;
        promise: Promise<UploadResult>;
    };
    touch(filepath: string, mtime?: Date, ctime?: Date): Promise<void>;
    scanFile(path: string): Promise<ReadDirItem[]>;
    readonly MainBundlePath: any;
    readonly ResourcesPath: any;
    readonly CachesDirectoryPath: any;
    readonly ExternalCachesDirectoryPath: any;
    readonly DocumentDirectoryPath: any;
    readonly ExternalDirectoryPath: any;
    readonly ExternalStorageDirectoryPath: any;
    readonly TemporaryDirectoryPath: any;
    readonly LibraryDirectoryPath: any;
    readonly PicturesDirectoryPath: any;
    readonly FileProtectionKeys: any;
    readonly Separator: any;
};
export default RNFS;
//# sourceMappingURL=index.d.ts.map